version: "3.8"

services:
  email-service: # Changed from "server" to match "container_name"
    container_name: email-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure
